# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77abaecd3384d43cc89373243e7b36b3c23e69765b7f2666d50a3302f57d73103e92c5f3c5f570228e255fc1131466677b66c4e8fc064e9b9ded66f3cb166d5c

test:
  secret_key_base: c845d981f5475c167e4d2b1580a0c0b93cd2fa9a0d994c7a167e675891f413a2a76d5ab9392aa6711fadc08accbfb5c3f353851273294714ed67260225b9213f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
