Listing.destroy_all
Board.destroy_all
Post.destroy_all
Note.destroy_all

caroline = User.create!(email: "caroline@gmail.com", password: "password")


base = Board.create(title: "Home Base", image: "http://www.homebasefix.com/images/1.png", user: caroline)
tutorials = Board.create(title: "Tutorials", image: "http://codecondo.com/wp-content/uploads/2014/04/5-Coding-Challenges-to-Help-You-Train-Your-Brain.jpg?x94435", user: caroline)
games = Board.create(title: "Games", image: "https://cnmingenuity.org/stemulus/wp-content/uploads/sites/6/2015/11/icon-ddcb-lg.png", user: caroline)
challenges = Board.create(title: "Challenges", image: "https://d30y9cdsu7xlg0.cloudfront.net/png/62765-200.png", user: caroline)
general = Board.create(title: "General", image: "https://webresourcesdepot.com/wp-content/uploads/05-cloud-css-pure-icon-1.jpg", user: caroline)
html = Board.create(title: "HTML", image: "http://icon-icons.com/icons2/656/PNG/512/web_development_coding_code_browse_browser_icon-icons.com_59980.png", user: caroline)
css = Board.create(title: "CSS", image: "https://cdn4.iconfinder.com/data/icons/smart-phone-computer/512/04-512.png", user: caroline)
design = Board.create(title: "Design", image: "https://creativenerds.co.uk/wp-content/uploads/2016/01/css-icons.jpg", user: caroline)
social = Board.create(title: "Networking", image: "http://parkviewsports.com/wp-content/uploads/EventPhotoFull_networking-concept-8015555.jpg", user: caroline)
jobs = Board.create(title: "Jobsearch", image: "https://media3.giphy.com/media/5fBH6zoAQg9dHK2ttsc/giphy.gif", user: caroline)
javascript = Board.create(title: "Javascript", image: "http://blog.flatironschool.com/wp-content/uploads/2013/11/Ruby-and-JavaScript.jpg", user: caroline)
ruby = Board.create(title: "Ruby and Rails", image: "https://www.google.com/search?q=ruby+on+rails&tbm=isch&source=lnms&sa=X&ved=0ahUKEwjU_vbfgMXTAhXGbSYKHZRVDzwQ_AUICCgD&biw=1440&bih=799#imgrc=r58ubApRuw8xrM:", user: caroline)



slack = Post.create(title: "Slack", image: "https://forger.typo3.org/images/slack.svg", url: "https://slack.com/")
github = Post.create(title: "Github", image: "https://assets-cdn.github.com/images/modules/logos_page/Octocat.png", url: "https://github.com/")
css_cheat_sheet = Post.create(title: "CSS2 Visual Cheat Sheet", image: "https://raw.githubusercontent.com/logeshpaul/Frontend-Cheat-Sheets/master/images/css2-cheatsheet-preview.png", url: "https://jserrao.github.io/FEWD-DC-29/lessons/class02/CSS2-Visual-Cheat-Sheet.pdf")
google_fonts = Post.create(title: "Google Fonts", image: "https://www.gstatic.com/images/icons/material/apps/fonts/1x/opengraph_color_1200dp.png", url: "https://fonts.google.com/")
html_cheat_sheet = Post.create(title: "HTML Tags Cheat Sheet", image: "https://jserrao.github.io/FEWD-DC-29/lessons/class01/html-tags.pdf", url: "https://jserrao.github.io/FEWD-DC-29/lessons/class01/html-tags.pdf")
hsl = Post.create(title: "HSL Color Picker", image: "http://best-web-design-tools.com/wp-content/uploads/2013/03/hsl-color-picker.jpg", url: "http://hslpicker.com/")
my_fonts = Post.create(title: "MyFonts", image: "http://www.underware.nl/case-studies/_previews/myfonts.jpg", url: "http://www.myfonts.com/")
html_sectioning = Post.create(title: "Treehouse HTML Sectioning Elements", image: "http://html5doctor.com/wp-content/uploads/2009/06/html5-after12.gif", url: "http://blog.teamtreehouse.com/use-html5-sectioning-elements")
jquery_doc = Post.create(title: "jQuery documentation", image: "https://joebuckle.me/wp-content/uploads/2015/09/jquery-logo.png", url: "http://api.jquery.com/")
oridomi = Post.create(title: "Oridomi", image: "https://www.bram.us/wordpress/wp-content/uploads/2012/11/Screen-Shot-2012-11-04-at-23.06.39-560x375.png", url: "http://oridomi.com/")
adobe_color = Post.create(title: "Adobe Color CC", image: "http://www.indesignskills.com/wp-content/uploads/2016/02/Color-wheel-analogous.jpg", url: "https://color.adobe.com/create/color-wheel/")
jquery_cheat_sheet = Post.create(title: "jQuery Cheat Sheet", image: "http://www.qlikblog.at/wp-content/uploads/2013/01/001_CheatSheet_oscarotero.png", url: "https://oscarotero.com/jquery/")
sage = Post.create(title: "Sage", image: "http://eddiepantoja.com/wp-content/uploads/2016/09/sage-og2.png", url: "https://roots.io/sage/")
foundation = Post.create(title: "Foundation", image: "http://foundation.zurb.com/assets/img/learn/features/svgs/code-reduction-01.svg", url: "http://foundation.zurb.com/")
canva = Post.create(title: "Canva", image: "http://blog.yapp.us/wp-content/uploads/2015/06/Marketing-Images-Made-Easy-with-Canva.jpg", url: "https://www.canva.com/")
color_names = Post.create(title: "CSS Color Names", image: "https://flatuicolors.com/img/facebook-share.jpg", url: "http://www.colors.commutercreative.com/grid/")
float_clear = Post.create(title: "CSS Float and Clear Explained", image: "https://phrasee.co/wp-content/uploads/2016/04/youtube.jpg", url: "https://www.youtube.com/watch?v=xara4Z1b18I")
zen = Post.create(title: "CSS Zen Garden", image: "http://www.mezzoblue.com/zengarden/screenshots/217.jpg", url: "http://www.mezzoblue.com/zengarden/alldesigns/")
sideways = Post.create(title: "Sideways Dictionary", image: "https://s3-eu-central-1.amazonaws.com/centaur-wp/creativereview/prod/content/uploads/2017/03/Sideways2.jpg", url: "https://sidewaysdictionary.com/#/")
commands = Post.create(title: "Command Line Fu", image: "https://i2.wp.com/makezine.com/wp-content/uploads/2009/02/command-line-fu.png?resize=1200%2C670&strip=all", url: "http://www.commandlinefu.com/commands/browse/sort-by-votes")
replit = Post.create(title: "Repl.it", image: "https://repl.it/public/images/logo-small-square.png", url: "https://repl.it/")
css_positioning = Post.create(title: "CSS Tricks Absolute, Relative, Fixed Positioning", image: "https://www.infragistics.com/community/cfs-filesystemfile.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/brent_5F00_schooley.metablogapi/8765.css_2D00_tricks_5F00_03149516.png", url: "https://css-tricks.com/absolute-relative-fixed-positioining-how-do-they-differ/")
css_flexbox = Post.create(title: "CSS Tricks Flexbox", image: "https://www.infragistics.com/community/cfs-filesystemfile.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/brent_5F00_schooley.metablogapi/8765.css_2D00_tricks_5F00_03149516.png", url: "https://css-tricks.com/snippets/css/a-guide-to-flexbox/")
css_diner = Post.create(title: "CSS Diner", image: "http://images.shejidaren.com/wp-content/uploads/2014/03/css-diner.gif?w=240", url: "http://flukeout.github.io/")
html_validator = Post.create(title: "HTML Validator", image: "https://addons.opera.com/media/CACHE/images/extensions/13/3913/1.0-rev1/images/shot2/b11d65c579f87273563c7a711bfa5632.jpg", url: "https://validator.w3.org/#validate_by_input")
css_validator = Post.create(title: "CSS Validator", image: "https://www.w3.org/Icons/valid-css-blue-v.svg", url: "https://jigsaw.w3.org/css-validator/#validate_by_input")
git_branching = Post.create(title: "Learn Git Branching", image: "https://log.cyconet.org/content/images/2013/02/learninggitbranching.png", url: "http://learngitbranching.js.org/lea")
serio = Post.create(title: "Serio Verify", image: "https://assets.awwwards.com/awards/sites_of_the_day/2016/06/awwwards-sotd-moods-Serio-Verify-1.jpg", url: "https://serioverify.com/")
hexagon_ideas = Post.create(title: "14 Cool Hexagon Web Design", image: "http://smashinghub.com/wp-content/uploads/2013/10/Hexagon-web-design-1-1024x538.png", url: "http://smashinghub.com/14-cool-hexagon-web-design.htm")
unsplash = Post.create(title: "Unsplash", image: "https://1095.unsplash.com/img/instant.jpg", url: "https://unsplash.com/")
design4 = Post.create(title: "Web Design in 4 Minutes", image: "http://jgthms.com/web-design-in-4-minutes/learn-web-design-in-4-minutes.png", url: "http://jgthms.com/web-design-in-4-minutes/")
chrome_tools = Post.create(title: "Chrome DevTools Tutorial", image: "https://developer.chrome.com/devtools/images/devtools-window.png", url: "https://developers.google.com/web/tools/chrome-devtools/inspect-styles/?hl=en")
javascript30 = Post.create(title: "Javascript30", image: "https://i1.wp.com/wptavern.com/wp-content/uploads/2017/01/javascript30.png?ssl=1", url: "https://javascript30.com/")
cats = Post.create(title: "Javascript for Cats", image: "http://jsforcats.com/images/substack-cats.png", url: "http://jsforcats.com/")
coderbyte = Post.create(title: "Coderbyte", image: "http://static.tumblr.com/f866c54b5d6c150711c388db68192dda/b0qpcxg/tBmo23nwq/tumblr_static_6y2rrmcnak8w0o8004kkcgosc.png", url: "https://coderbyte.com/challenges/")
this = Post.create(title: "Understand Javascript This", image: "https://s3-torquehhvm-wpengine.netdna-ssl.com/uploads/2016/01/how-to-learn-javascript-properly.jpg", url: "http://javascriptissexy.com/understand-javascripts-this-with-clarity-and-master-it/")
poignant = Post.create(title: "Whys Poignant Guide To Ruby", image: "http://poignant.guide/images/2007-cover-shut.jpg", url: "http://rubyinside.com/media/poignant-guide.pdf")
combat = Post.create(title: "Code Combat", image: "https://codecombat.com/images/pages/base/logo.png", url: "https://codecombat.com/")
sololearn = Post.create(title: "Solo Learn", image: "https://i.ytimg.com/vi/o8kT5c_4PAc/maxresdefault.jpg", url: "https://www.sololearn.com/Courses/")
codewars = Post.create(title: "codewars", image: "http://iwanttolearnruby.com/images/codewars.png", url: "https://www.codewars.com/")
portfolio_designs = Post.create(title: "Pinterest 17 Best Ideas About Online Portfolio Design", image: "http://az616578.vo.msecnd.net/files/2016/02/22/635917154065999535-1437171416_Pinterest-begeek-wallpaper.jpg", url: "https://www.pinterest.com/explore/online-portfolio-design/")
siteinspire = Post.create(title: "site inspire", image: "https://18482-presscdn-0-9-pagely.netdna-ssl.com/wp-content/uploads/2010/11/siteinspire.png", url: "https://www.siteinspire.com/")
pixabay = Post.create(title: "pixabay", image: "http://www.userlogos.org/files/logos/1air2philou/pixabay-button.png", url: "https://pixabay.com/pi")
monster = Post.create(title: "Monster", image: "http://logos-download.com/wp-content/uploads/2016/05/Monster_Jobs_logo_logotype.png", url: "https://www.monster.com/")
rails_guide = Post.create(title: "Getting Started with Rails", image: "http://iwanttolearnruby.com/images/railsguides.png", url: "http://guides.rubyonrails.org/getting_started.html")
tech_meetup = Post.create(title: "DC Tech Meetup", image: "http://i.imgur.com/kTgDs.gif", url: "https://www.meetup.com/DC-Tech-Meetup/")
linkedin = Post.create(title: "LinkedIn", image: "https://www.storagecraft.com/blog/wp-content/uploads/2016/06/LinkedIn.jpg", url: "https://www.linkedin.com")
typewolf = Post.create(title: "Typewolf", image: "https://www.typewolf.com/assets/img/typewolf-og.png", url: "https://www.typewolf.com/")
gems = Post.create(title: "RubyGems", image: "http://www.opensourcerails.com/screens/rubygems/cover.jpg", url: "https://rubygems.org/")

Listing.create(board: base, post: slack)
Listing.create(board: base, post: github)
Listing.create(board: css, post: css_cheat_sheet)
Listing.create(board: design, post: google_fonts)
Listing.create(board: html, post: html_cheat_sheet)
Listing.create(board: design, post: hsl)
Listing.create(board: design, post: my_fonts)
Listing.create(board: html, post: html_sectioning)
Listing.create(board: javascript, post: jquery_doc)
Listing.create(board: design, post: oridomi)
Listing.create(board: design, post: adobe_color)
Listing.create(board: javascript, post: jquery_cheat_sheet)
Listing.create(board: design, post: sage)
Listing.create(board: design, post: foundation)
Listing.create(board: design, post: canva)
Listing.create(board: design, post: color_names)
Listing.create(board: tutorials, post: float_clear)
Listing.create(board: design, post: zen)
Listing.create(board: general, post: sideways)
Listing.create(board: general, post: commands)
Listing.create(board: general, post: replit)
Listing.create(board: css, post: css_positioning)
Listing.create(board: css, post: css_flexbox)
Listing.create(board: games, post: css_diner)
Listing.create(board: css, post: css_diner)
Listing.create(board: html, post: html_validator)
Listing.create(board: css, post: css_validator)
Listing.create(board: games, post: git_branching)
Listing.create(board: design, post: serio)
Listing.create(board: design, post: hexagon_ideas)
Listing.create(board: design, post: unsplash)
Listing.create(board: design, post: design4)
Listing.create(board: general, post: chrome_tools)
Listing.create(board: challenges, post: javascript30)
Listing.create(board: javascript, post: cats)
Listing.create(board: challenges, post: coderbyte)
Listing.create(board: javascript, post: this)
Listing.create(board: ruby, post: poignant)
Listing.create(board: challenges, post: combat)
Listing.create(board: tutorials, post: sololearn)
Listing.create(board: challenges, post: codewars)
Listing.create(board: design, post: portfolio_designs)
Listing.create(board: design, post: siteinspire)
Listing.create(board: design, post: pixabay)
Listing.create(board: jobs, post: monster)
Listing.create(board: ruby, post: rails_guide)
Listing.create(board: social, post: tech_meetup)
Listing.create(board: social, post: linkedin)
Listing.create(board: css, post: float_clear)
Listing.create(board: general, post: git_branching)
Listing.create(board: tutorials, post: canva)
Listing.create(board: design, post: typewolf)
Listing.create(board: ruby, post: gems)

Note.create(body: "Cool jQuery plug-in to create illusion of folding up web pages", post: oridomi)
Note.create(body: "WordPress starter theme", post: sage)
Note.create(body: "Front-end framework", post: foundation)
Note.create(body: "Design tutorials and tools", post: canva)
Note.create(body: "Free, do what you want, high res photos", post: unsplash)
Note.create(body: "Covers c++, java, python, javascript, php, c#, swift, ruby, jquery, html, css, sql", post: sololearn)